### ISSUE TITLE
Consider removing end indices from indices property

### ISSUE THREAD

**Issue by marpri** [tc39/proposal-regexp-match-indices#34]
For the full match, the returned array currently includes an extra property index that contains the start index of the full match and doesn't include the end index. The end index would be redundant since it can be computed by adding the matched string length to the start index.

Assuming the return array will still contain the full match and all captured substrings, why not using the same reasoning for captured substrings by including only start indices and excluding end indices. The start indices would be stored in the `indices` array in the same order as captured substrings are stored in the main returned array, so this solution would be neat to use and more consistent with the current way of using RegExp. There would still remain one redundancy, though: `m1.indices[0] === m1.index`.

Example:
```js
const re1 = /a+(?<Z>z)?/;
const s1 = 'xaaaz';
const m1 = re1.exec(s1);

for (let i = 0; i < m1.length; i++) {
  console.log(m1[i]); // captured substring
  console.log(m1.indices[i]); // start index
  console.log(m1.indices[i] + m1[i].length); // end index if needed
}

// aaaz
// 1
// 5
// z
// 4
// 5
```

Or maybe I'm just missing something.

**Comment by rbuckton** [comment]
See https://github.com/tc39/proposal-regexp-match-indices/issues/30#issuecomment-519404284 for the rationale as to why a "tuple"-like array was chosen.

As this proposal is already at Stage 3, I don't foresee any further changes to the proposal other than those needed to address implementer concerns.
