### ISSUE TITLE
spec bug: wrong assert in GetStringIndex

### ISSUE THREAD

**Issue by targos** [tc39/proposal-regexp-match-indices#40]
In `GetStringIndex`, there's an assertion that `e < Input.length`, though the next step has a special case for when `e` is greater than or equal to `Input.length`.

https://github.com/tc39/proposal-regexp-match-indices/blob/58c4881e271529acf880b238dd26341a0e1db0f6/spec/sec-properties-of-the-regexp-prototype-object-patch.html#L105-L106

**Comment by rbuckton** [comment]
I can either remove that part of the assert, or change the second part of the assert to `< 2³²-1`
